version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alquileres
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria123
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mariaphpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  backend:
    build: ./Backend
    container_name: maria_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env # Docker automáticamente carga las variables del archivo .env
